# Tokenizers (TensorFlow)

Install the Transformers, Datasets, and Evaluate libraries to run this notebook.

In [ ]:
!pip install datasets evaluate transformers[sentencepiece]

In [9]:
tokenized_text = "Jim Henson was a puppeteer".split()
print(tokenized_text)

['Jim', 'Henson', 'was', 'a', 'puppeteer']


In [10]:
tokenizer = BertTokenizer.from_pretrained("bert-base-cased")

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

In [11]:
tokenizer("Using a Transformer network is simple")

{'input_ids': [101, 7993, 170, 13809, 23763, 2443, 1110, 3014, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
tokenizer.save_pretrained("directory_on_my_computer")

In [12]:
tokenizer = BertTokenizer.from_pretrained("bert-base-cased")

sequence = "Using a Transformer network is simple"
tokens = tokenizer.tokenize(sequence)

print(tokens)

['Using', 'a', 'Trans', '##former', 'network', 'is', 'simple']


In [13]:
ids = tokenizer.convert_tokens_to_ids(tokens)

print(ids)

[7993, 170, 13809, 23763, 2443, 1110, 3014]


In [14]:
decoded_string = tokenizer.decode([7993, 170, 11303, 1200, 2443, 1110, 3014])
print(decoded_string)

Using a transformer network is simple


In [5]:
from transformers import BertTokenizer, TFBertModel

sequence = "Using a Transformer network tokenizer is simple."

tokenizer = BertTokenizer.from_pretrained("bert-base-cased")
input = tokenizer(sequence)
print(input)

{'input_ids': [101, 7993, 170, 13809, 23763, 2443, 22559, 17260, 1110, 3014, 119, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [8]:
import tensorflow as tf

model = TFBertModel.from_pretrained("bert-base-cased")

model_input = tf.constant(input["input_ids"])[None, :]

outputs = model(model_input)
print(outputs)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 12, 768), dtype=float32, numpy=
array([[[ 0.63353646,  0.09759484,  0.1438223 , ..., -0.17932707,
          0.1910656 ,  0.24268341],
        [ 0.7219239 , -0.18676242,  0.6580373 , ..., -0.2691033 ,
          0.05060793,  0.07185888],
        [ 0.5630603 , -0.08478543,  0.01277313, ...,  0.56513   ,
          0.41754085,  0.29724136],
        ...,
        [ 0.53009   , -0.19872059,  0.4364952 , ...,  0.3784231 ,
          0.09680112,  0.3579647 ],
        [ 0.14057761, -0.06898865,  0.376986  , ...,  0.0404541 ,
          0.05980017, -0.13688569],
        [ 1.2452095 ,  0.4296373 ,  0.18943791, ...,  0.1845115 ,
          0.17698398, -0.05684034]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-7.01632500e-01,  4.41352397e-01,  9.99853909e-01,
        -9.86589968e-01,  9.47826385e-01,  7.83831000e-01,
         9.60934639e-01, -9.85135376e-01, -9.30090964e-