# Models (TensorFlow)

Install the Transformers, Datasets, and Evaluate libraries to run this notebook.

In [3]:
from transformers import BertConfig, TFBertModel

# Building the config
config = BertConfig()

# Building the model from the config
model = TFBertModel(config)

In [4]:
print(config)

BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.50.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



In [5]:
model = TFBertModel.from_pretrained("bert-base-cased")

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [7]:
encoded_sequences = [
    [101, 7592, 999, 102],
    [101, 4658, 1012, 102],
    [101, 3835, 999, 102],
]

In [8]:
import tensorflow as tf

model_inputs = tf.constant(encoded_sequences)

In [9]:
output = model(model_inputs)

In [10]:
print(output)

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(3, 4, 768), dtype=float32, numpy=
array([[[ 4.4495744e-01,  4.8276284e-01,  2.7797198e-01, ...,
         -5.4032274e-02,  3.9393425e-01, -9.4769992e-02],
        [ 2.4942899e-01, -4.4092962e-01,  8.1772339e-01, ...,
         -3.1916568e-01,  2.2992219e-01, -4.1171715e-02],
        [ 1.3667546e-01,  2.2517854e-01,  1.4501992e-01, ...,
         -4.6914592e-02,  2.8224233e-01,  7.5565845e-02],
        [ 1.1788858e+00,  1.6738570e-01, -1.8187097e-01, ...,
          2.4671350e-01,  1.0440764e+00, -6.1971312e-03]],

       [[ 3.6435828e-01,  3.2463297e-02,  2.0257683e-01, ...,
          6.0110353e-02,  3.2451293e-01, -2.0995583e-02],
        [ 7.1865958e-01, -4.8725206e-01,  5.1740402e-01, ...,
         -4.4012007e-01,  1.4553043e-01, -3.7544727e-02],
        [ 3.3223230e-01, -2.3270901e-01,  9.4876081e-02, ...,
         -2.5268167e-01,  3.2172003e-01,  8.1142318e-04],
        [ 1.2523208e+00,  3.5754293e-01,

In [11]:
sequences = ["Hello!", "Cool.", "Nice!"]

In [12]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-cased")
input = tokenizer(sequences, padding=True, truncation=True)
print(input)

{'input_ids': [[101, 8667, 106, 102], [101, 13297, 119, 102], [101, 8835, 106, 102]], 'token_type_ids': [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]}


In [13]:
model_input_id = tf.constant(input["input_ids"])
model_attention_mask = tf.constant(input["attention_mask"])

output2 = model(model_input_id, model_attention_mask)
print(output2)

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(3, 4, 768), dtype=float32, numpy=
array([[[ 0.62828964,  0.21656758,  0.560512  , ...,  0.01361646,
          0.615793  , -0.17120235],
        [ 0.6108095 , -0.22526626,  0.92628855, ..., -0.30280808,
          0.4499951 , -0.07135769],
        [ 0.8039674 ,  0.18094489,  0.70756704, ..., -0.0684973 ,
          0.48369724, -0.07738485],
        [ 1.3290284 ,  0.2359512 ,  0.4566581 , ...,  0.1508819 ,
          0.9621055 , -0.48411724]],

       [[ 0.31276435,  0.17181471,  0.20987779, ..., -0.0721087 ,
          0.4918776 , -0.13833432],
        [ 0.15445176, -0.37572706,  0.7187129 , ..., -0.31295148,
          0.2821989 ,  0.18830812],
        [ 0.41229045,  0.37207627,  0.54835176, ...,  0.07883389,
          0.56807595, -0.27571857],
        [ 0.8356334 ,  0.39642993, -0.41206455, ...,  0.183796  ,
          1.6364969 , -0.4806332 ]],

       [[ 0.53993607,  0.25642586,  0.25112194, ..., -0.176017